from scripts.qwen3_vl_embedding import Qwen3VLEmbedder
import numpy as np
import torch

def generate_embeddings(inputs, model_name_or_path="Qwen/Qwen3-VL-Embedding-2B", **kwargs):
    """
    Generate embeddings for the given inputs using Qwen3-VL-Embedding model.
    
    Args:
        inputs: List of input documents/queries.
        model_name_or_path: Path or name of the model.
        **kwargs: Additional arguments for Qwen3VLEmbedder (e.g., torch_dtype, attn_implementation).
        
    Returns:
        Embeddings generated by the model.
    """
    # Initialize the Qwen3VLEmbedder model
    # We recommend enabling flash_attention_2 for better acceleration and memory saving if supported
    # model = Qwen3VLEmbedder(model_name_or_path=model_name_or_path, torch_dtype=torch.float16, attn_implementation="flash_attention_2")
    
    # Initialize with provided arguments
    model = Qwen3VLEmbedder(model_name_or_path=model_name_or_path, **kwargs)
    
    # Process the inputs to get embeddings
    embeddings = model.process(inputs)
    return embeddings

if __name__ == "__main__":
    # Example usage
    
    # Specify the model path
    default_model_path = "Qwen/Qwen3-VL-Embedding-2B"
    
    # Example documents (placeholder as original code had 'documents' undefined)
    # In a real scenario, replace this with actual documents
    documents = [
        "This is a test document for embedding generation.",
        "Another example text."
    ]
    
    print(f"Generating embeddings for {len(documents)} documents...")
    
    try:
        # Process the inputs to get embeddings
        embeddings = generate_embeddings(documents, model_name_or_path=default_model_path)
        print("Embeddings generated successfully.")
        # print(embeddings) # Uncomment to see the embeddings
    except Exception as e:
        print(f"An error occurred: {e}")
